# Generated by Django 5.0.6 on 2024-07-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_modelo_veiculo"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="foto_veiculo",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
