# Generated by Django 5.0.6 on 2024-07-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="veiculo",
            old_name="Acessorio",
            new_name="acessorios",
        ),
    ]
